version: "3.7"
services:
  nginx-service:
    build: ./nginx 
    ports:
      - '8080:8080' 
      - '9090:9090' 
    depends_on:
      - grafana-service
      - nodered-service
  nodered-service:
    build: ./nodered
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./data/nodered # physical location in host to keep persistent data. 
        target: /data # where nodered saves data to
  mosquitto-service:
    build: ./mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  influxdb-service:
    build: ./influxdb
    volumes:
      - type: bind
        source: ./data/influxdb
        target: /var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
  grafana-service:
    build: ./grafana
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./data/grafana
        target: /var/lib/grafana
    depends_on:
      - influxdb-service
    # environment:
    #   - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
    #   - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

