version: '3.7'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - type: bind
        source: ./config
        target: /etc/influxdb 
      - type: bind
        source: ./data
        target: /var/lib/influxdb
    # environment:
    #   - INFLUXDB_DB=db0
    #   - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
    #   - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  